app_port = "8080"
query_complexity_limit = 81

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "7050"
db_name = "chat_db"
[smtp]
author = "http-cute-chat"
host = "smtp.yandex.ru"
port = 587
[logger]
level = "Debug"
mongo_db_cluster = "log-db.5qcx4.mongodb.net"
db_name = "logs"